# Default values for postal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

image:
  repository: ghcr.io/postalserver/postal
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

commonsAnnotations: {}
  # argocd.argoproj.io/sync-wave: "1"
  # helm.sh/hook: "pre-install,pre-upgrade"
  # helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
  # helm.sh/hook-weight: "1"

global:
  # use an existing secret instead of the automaticaly generated one
  existingSecretName: ""
  # -- key used to sign emails.
  # Generate it using openssl genrsa -out path/to/signing.key 2048
  signingKey: ""
  # -- the secret key used to sign and encrypt cookies and session data in the application.
  # Generate it using openssl rand -hex 64
  railsSecretKey: ""
  # The hostname that the Postal web interface runs on
  webHostname: localhost
  # The HTTP protocol to use for the Postal web interface
  webProtocol: http
  # The hostname that the Postal SMTP server runs on
  smtpHostname: localhost
  # Should IP pools be enabled for this installation?
  useIpPools: false
  # The maximum number of delivery attempts
  maximumDeliveryAttempts: 18
  # The number of days to hold a message before they will be expired
  maximumHoldExpiryDays: 7
  # The number of days an address will remain in a suppression list before being removed
  suppressionListAutomaticRemovalDays: 30
  # The default threshold at which a message should be treated as spam
  spamThreshold: 5
  # The default threshold at which a message should be treated as spam failure
  spamFailureThreshold: 20
  # Domain verification and checking usually checks with a domain's nameserver. Enable this to check with the server's local nameservers.
  useLocalNsForDomainVerification: false
  # Append a Resend-Sender header to all outgoing e-mails
  useResentSenderHeader: true
  # An array of SMTP relays in the format of smtp://host:port
  smtpRelays: ""
  # An array of IP addresses to trust for proxying requests to Postal (in addition to localhost addresses)
  trustedProxies: ""

  # This secret must contain the following keys
  ## - mariadb-password
  ## - signing-key (The signing.key can be generated using the following command: openssl genrsa -out path/to/signing.key 2048)
  ## - rails-secret-key  (the rail-secret-key can be generated using the following command: openssl rand -hex 64)
  ## - smtp-cert (SMTP server's TLS certificate)
  ## - smtp-key (SMTP server's TLS private key)
  secretName: "postal"

database:
  # The maximum size of the MariaDB connection pool
  poolSize: 5
  # The encoding to use when connecting to the MariaDB database
  encoding: utf8mb4

logging:
  # Enable the Postal logger to log to STDOUT
  enabled: true
  # Enable the default Rails logger
  railsLog: false
  # A DSN which should be used to report exceptions to Sentry
  sentryDsn: ""
  # Enable highlighting of log lines
  highlighting: false

dns:
  # The names of the default MX records | ["mx1.postal.example.com", "mx2.postal.example.com"]
  mxRecords: ""
  # The location of the SPF record
  spfInclude: ""
  # The return path hostname
  returnPathDomain: ""
  # The domain to use for hosting route-specific addresses
  routeDomain: ""
  # The CNAME which tracking domains should be pointed to
  trackDomain: ""

# This is the main web server that handles all web traffic for Postal's admin interface and open/click tracking requests.
# You can run multiple web servers and load balance between them to add additional capacity for web requests.
web:
  replicaCount: 1
  imagePullSecrets: []
  nameOverride: "postal-web"
  fullnameOverride: "postal-web"

  containerPort: 5000

  # The maximum number of threads which can be used by the web server
  maxThreads: 5

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false
    className: ""
    annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}


# Smtp server deployment
smtp:
  replicaCount: 1
  imagePullSecrets: []
  nameOverride: "postal-smtp"
  fullnameOverride: "postal-smtp"

  containerPort: 25

  #  The default port for the SMTP server health server and metrics to listen on
  healthAndMetricsServerPort: 9090

  # Enable proxy protocol for use behind some load balancers
  proxyProtocol: false

  # Enable connection logging
  logConnections: false

  # The maximum message size to accept from the SMTP server (in MB)
  maxMessageSize: 14

  # A regular expression to use to exclude connections from logging
  logIpAddressExclusionMatcher: ""

  # Enabled TLS
  # Postal secret must contains SMTP server's TLS private key and SMTP server's TLS certificate
  tls:
    enabled: false

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
    # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  service:
    type: ClusterIP
    port: 25

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Consumer deployment.
# This runs a worker which will receive jobs from the message queue.
# Essentially, this handles processing all incoming and outgoing e-mail.
# If you're needing to process lots of e-mails, you may wish to run more than one of these. You can run as many of these as you wish.
worker:
  replicaCount: 1
  imagePullSecrets: []
  nameOverride: "postal-worker"
  fullnameOverride: "postal-worker"

  # The default port for the worker health server and metrics to listen on
  healthAndMetricsServerPort: 9090

  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  podAnnotations: {}

  podSecurityContext: {}
  # fsGroup: 2000

  securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

  service:
    type: ClusterIP

  resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Enable ClamAV for message inspection
clamAv:
  enabled: false
  # The host of the ClamAV server
  host: ""
  # The port of the ClamAV server
  port: 2000

# Enable SpamAssassin for message inspection
spamAssassin:
  enabled: false
  # The host of the ClamAV server
  host: ""
  # The port of the ClamAV server
  port: 783

# dependencies
mariadb:
  # check available values here: https://artifacthub.io/packages/helm/bitnami/mariadb?modal=values-schema
  enabled: true
  # TODO: we should switch to templating for the name to avoid using reference to fullname override everywhere
  fullnameOverride: postal-mariadb
  auth:
    database: "postal"
    username: "postal"
    password: "postal"
  initdbScripts:
    # NOTE: postal is creating postal-server-* databases to handle postal mail servers configuration
    grant_privileges.sql: |
      GRANT ALL PRIVILEGES ON `postal%`.* TO 'postal'@'%' WITH GRANT OPTION;

jobs:
  # Bootstrap MariaDB
  initialize:
    enable: true # is it the right value ?
    image:
      repository: ghcr.io/postalserver/postal
      pullPolicy: IfNotPresent
      # Overrides the image tag whose default is the chart appVersion.
      tag: ""

    imagePullSecrets: []
    nameOverride: "postal-initialize"
    fullnameOverride: "postal-initialize"

    serviceAccount:
      # Specifies whether a service account should be created
      create: false
      # Annotations to add to the service account
      annotations: {}
      # The name of the service account to use.
      # If not set and create is true, a name is generated using the fullname template
      name: ""

    podAnnotations: {}

    podSecurityContext: {}
    # fsGroup: 2000

    securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000

    resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

    autoscaling:
      enabled: false
      minReplicas: 1
      maxReplicas: 100
      targetCPUUtilizationPercentage: 80
      # targetMemoryUtilizationPercentage: 80

    nodeSelector: {}

    tolerations: []

    affinity: {}
