---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: friday
      time: "04:00"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: friday
      time: "04:00"
    groups:
      docker-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "helm"
    directory: "/postal"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: friday
      time: "04:00"
    groups:
      helm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
      day: friday
      time: "04:00"
    groups:
      pip-dependencies:
        patterns:
          - "*"
