{{- if and .Values.smtp.tls.enabled (eq .Values.smtp.tls.source "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "postal.smtp.fullname" . }}
  {{- $merged := merge .Values.commonsAnnotations .Values.smtp.tls.annotations }}
  {{- if $merged }}
  annotations:
    {{- range $key, $value := $merged }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  secretName: {{ include "postal.smtp.fullname" . }}-tls
  dnsNames:
    {{- range .Values.smtp.tls.hosts }}
    - {{ . }}
    {{- end }}
  usages:
    - digital signature
    - key encipherment
  issuerRef:
    name: {{ .Values.smtp.tls.certManager.issuer.name }}
    kind: {{ .Values.smtp.tls.certManager.issuer.kind }}
    group: {{ .Values.smtp.tls.certManager.issuer.group }}
{{- else if and .Values.smtp.tls.enabled (eq .Values.smtp.tls.source "self-signed") }}
{{- $ca := genCA "test-ca" 365 }}
{{- $host := include "postal.smtp.fullname" . }}
{{- if and .Values.smtp.tls.hosts (gt (len .Values.smtp.tls.hosts) 0) }}
{{- $host = index .Values.smtp.tls.hosts 0 }}
{{- end }}
{{- $cert := genSignedCert $host nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postal.smtp.fullname" . }}-tls
  labels:
    {{- include "postal.labels" . | nindent 4 }}
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
