{{- if not .Values.global.existingSecretName }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.secretName | quote }}
  labels:
    {{- include "postal.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonsAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  {{- if .Values.global.signingKey }}
  signing-key: {{ .Values.global.signingKey | b64enc | quote }}
  {{- else }}
  signing-key: {{ genPrivateKey "rsa" | b64enc | quote }}
  {{- end }}
  {{- if .Values.global.railsSecretKey }}
  rails-secret-key: {{ .Values.global.railsSecretKey | b64enc | quote }}
  {{- else }}
  rails-secret-key: {{ randAlphaNum 128 | b64enc | quote }}
  {{- end }}
{{- end }}
