{{- if not .Values.global.existingSecretName }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.secretName | quote }}
  labels:
    {{- include "postal.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.commonsAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  mariadb-password: {{ .Values.mariadb.auth.password | b64enc | quote }}
  signing-key: {{ .Values.global.signingKey | required "You must provide a global.signingKey value" | b64enc | quote }}
  rails-secret-key: {{ .Values.global.railsSecretKey | required "You must provide a global.railsSecretKey value" | b64enc | quote }}
{{- end }}
