---
name: Shared - Continuous Integration for common tasks

on: # yamllint disable-line rule:truthy
  workflow_call:

permissions:
  actions: read
  contents: read
  statuses: write
  security-events: write

jobs:
  linter:
    uses: hoverkraft-tech/ci-github-common/.github/workflows/linter.yml@6857ef6d10f704e0998aa4955282f27d1b9be778 # 0.23.1
    permissions:
      actions: read
      contents: read
      statuses: write
      security-events: write
    with:
      # FIXME: Remove useless linters on next super-linter release
      linter-env: |
        VALIDATE_KUBERNETES_KUBECONFORM=false

  tests-charts:
    name: Tests - Charts
    runs-on: "ubuntu-latest"
    permissions:
      contents: read
    steps:
      - name: Test helm charts
        uses: hoverkraft-tech/ci-github-container/actions/helm/test-chart@f9e149b6cdfa8443994994f10085691a57b8cf0e # 0.27.1
        with:
          helm-repositories: |
            bitnami https://charts.bitnami.com/bitnami
