---
name: 🚀 Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: read
  contents: read
  statuses: write
  security-events: write

jobs:
  check-branches:
    name: Check branches
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]]; then
            echo "This action can only be run on the ${{ github.event.repository.default_branch }} branch"
            exit 1
          fi
          echo "Branch check passed. Proceeding with the release."
  ci:
    needs: check-branches
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml

  release:
    needs: ci
    name: Release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.create-release.outputs.tag }}
    steps:
      - id: create-release
        uses: hoverkraft-tech/ci-github-publish/actions/release/create@7ce3b41507f05379e3658efe955327873c2654b4 # 0.7.1

  release-chart:
    name: "Release Helm Chart"
    needs: release
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: hoverkraft-tech/ci-github-container/actions/helm/release-chart@f9e149b6cdfa8443994994f10085691a57b8cf0e # 0.27.1
        with:
          chart: postal
          path: ./postal
          tag: ${{ needs.release.outputs.tag }}
          oci-registry: ghcr.io
          oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
          update-tag-paths: .version

      - uses: hoverkraft-tech/ci-github-common/actions/create-and-merge-pull-request@6857ef6d10f704e0998aa4955282f27d1b9be778 # 0.23.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-chart-${{ needs.release.outputs.tag }}
          title: "ci: release chart ${{ needs.release.outputs.tag }}"
          body: Release app and chart version ${{ needs.release.outputs.tag }}
          commit-message: |
            ci: release chart ${{ needs.release.outputs.tag }}

            [skip ci]
