---
name: 🚀 Release

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-branches:
    name: Check branches
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        run: |
          if [[ "${{ github.ref_name }}" != "${{ github.event.repository.default_branch }}" ]]; then
            echo "This action can only be run on the ${{ github.event.repository.default_branch }} branch"
            exit 1
          fi
          echo "Branch check passed. Proceeding with the release."

  ci:
    needs: check-branches
    name: Continuous Integration
    uses: ./.github/workflows/__shared-ci.yml
    permissions:
      actions: read
      contents: read
      security-events: write
      statuses: write
    secrets: inherit

  release:
    needs: ci
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.create-release.outputs.tag }}
    steps:
      - id: create-release
        uses: hoverkraft-tech/ci-github-publish/actions/release/create@5ff7d4c3910971ed53834becd5967271b4e228cf # 0.21.1

  release-chart:
    name: "Release Helm Chart"
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
    steps:
      - id: release
        uses: hoverkraft-tech/ci-github-container/actions/helm/release-chart@a0bab9151cc074af9f6c8204ab42a48d2d570379 # 0.30.6
        with:
          chart: postal
          path: ./postal
          tag: ${{ needs.release.outputs.tag }}
          oci-registry: ghcr.io
          oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
          update-tag-paths: .version

      - uses: hoverkraft-tech/ci-github-common/actions/create-and-merge-pull-request@f24ce3360a8abf9bf386a62ab13d0ae5de5f9d13 # 0.31.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: release-chart-${{ needs.release.outputs.tag }}
          title: "ci: release chart ${{ needs.release.outputs.tag }}"
          body: Release app and chart version ${{ needs.release.outputs.tag }}
          commit-message: |
            ci: release chart ${{ needs.release.outputs.tag }}

            [skip ci]
